### ISSUE TITLE
buildcrx.sh 

### ISSUE THREAD

**Issue by flysssss** [kevmo314/magic-copy#1]
how  to use this file? According to the process, the Google plugin cannot be loaded

**Comment by flysssss** [comment]
![image](https://user-images.githubusercontent.com/100752067/230563685-f9e9a281-3c7e-4399-895a-d7c1db381efe.png)

**Comment by kevmo314** [comment]
It requires a few arguments: https://github.com/kevmo314/magic-copy/blob/main/.github/workflows/build.yml#L25

You can omit the private key, but actually building the crx is not necessary you can install the extension by zipping the directory

**Comment by kevmo314** [comment]
I've added some build instructions as well as a `Dockerfile` which should aid in building the extension from scratch: https://github.com/kevmo314/magic-copy#building
