### ISSUE TITLE
Option to crop to selected mask

### ISSUE THREAD

**Issue by digiwombat** [kevmo314/magic-copy#14]
Hey! First off, love the implementation and thanks for your work. Glad to see local mode implemented.

When selecting smaller parts of a larger image, the overall image size remains the same. It'd be great to be able to trim the transparent edge pixels so the resulting file doesn't need further cropping or editing in an external program. Making it an option would be best for people who want to keep the same image size for easy overlaying/compositing.

**Comment by kevmo314** [comment]
This seems like a great idea, it probably makes sense to make it the default given how much padding there is.

We could probably do something like this before exporting https://stackoverflow.com/a/22267731/86433

**Comment by digiwombat** [comment]
Yep, looks like it should work fine. I agree with it being default. Browser use-case is mostly going to be quick clipping, I imagine, so it's likely to be the expected outcome for most users.
