### ISSUE TITLE
support locally hosted version?

### ISSUE THREAD

**Issue by jadedgnome** [kevmo314/magic-copy#3]
can you add support for a locally run instance of segment anything?

**Comment by kevmo314** [comment]
Sure, that's a good idea. I'll add this soon.

**Comment by kevmo314** [comment]
I've added an extension setting to configure the server endpoint. Additionally, the README has some instructions on how to run your own server as well as a sample example server to get the API right. Thanks for the suggestion!	:)

https://github.com/kevmo314/magic-copy/commit/996680f4d36c3959be804950e6725dbc5058ae62
