### ISSUE TITLE
Are there any plans for Firefox support?

### ISSUE THREAD

**Issue by Fadyio** [kevmo314/magic-copy#9]
Are there any plans for Firefox support?

**Comment by kevmo314** [comment]
According to https://www.extensiontest.com/ the extension should be compatible. I'll look into what needs to be done to get it on the addons page :)

**Comment by kevmo314** [comment]
I've submitted the extension for review for Firefox. It was pretty simple, only a few metadata changes.

**Comment by Fadyio** [comment]
@kevmo314 Thank you
